import {
  Search,
  PencilRuler,
  Code2,
  FlaskConical,
  Rocket,
  RefreshCw,
  GraduationCap,
  Zap,
  Building2,
  Award,
  Briefcase,
  Target,
  Flag,
  Sparkles,
  BrainCircuit,
  LayoutPanelLeft,
  Atom,
  Cloud,
  Gauge,
  ShieldCheck,
  CalendarCheck,
  Calendar,
  FolderKanban,
  Layers,
  GitCommitHorizontal,
  Coffee,
  Mail,
  AtSign,
  Server,
  Database,
  GitBranch,
  Wrench,
  Terminal,
  type LucideIcon,
} from "lucide-react";

const registry: Record<string, LucideIcon> = {
  search: Search,
  "pencil-ruler": PencilRuler,
  "code-2": Code2,
  "flask-conical": FlaskConical,
  rocket: Rocket,
  "refresh-cw": RefreshCw,
  "graduation-cap": GraduationCap,
  zap: Zap,
  "building-2": Building2,
  award: Award,
  briefcase: Briefcase,
  target: Target,
  flag: Flag,
  sparkles: Sparkles,
  "brain-circuit": BrainCircuit,
  "layout-panel-left": LayoutPanelLeft,
  atom: Atom,
  cloud: Cloud,
  gauge: Gauge,
  "shield-check": ShieldCheck,
  "calendar-check": CalendarCheck,
  calendar: Calendar,
  "folder-kanban": FolderKanban,
  layers: Layers,
  "git-commit-horizontal": GitCommitHorizontal,
  coffee: Coffee,
  github: Code2,
  linkedin: Briefcase,
  mail: Mail,
  twitter: AtSign,
  server: Server,
  database: Database,
  "git-branch": GitBranch,
  wrench: Wrench,
  terminal: Terminal,
};

export function Icon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Component = registry[name] ?? Sparkles;
  return <Component className={className} aria-hidden="true" />;
}
